from tkinter import *


class NumericKeyboard:

    def __init__(self, root):
        self.isCapitals = False
        self.frame = Frame(root, background="white", height=224)
        self.frame.pack(side=BOTTOM, fill=X)

        self.firstRow = Frame(self.frame)
        self.firstRow.pack(side=TOP)
        self.secondRow = Frame(self.frame)
        self.secondRow.pack(side=TOP)
        self.thirdRow = Frame(self.frame)
        self.thirdRow.pack(side=TOP)
        self.fourthRow = Frame(self.frame)
        self.fourthRow.pack(side=BOTTOM)

        self.button1 = Button(self.firstRow, text="1")
        self.button2 = Button(self.firstRow, text="2")
        self.button3 = Button(self.firstRow, text="3")
        self.button4 = Button(self.firstRow, text="4")
        self.button5 = Button(self.firstRow, text="5")
        self.button6 = Button(self.firstRow, text="6")
        self.button7 = Button(self.firstRow, text="7")
        self.button8 = Button(self.firstRow, text="8")
        self.button9 = Button(self.firstRow, text="9")
        self.button0 = Button(self.firstRow, text="0")
        self.deleteButton = Button(self.firstRow, text=u"\u232B")

        self.buttonExp = Button(self.secondRow, text="!")
        self.buttonAt = Button(self.secondRow, text="@")
        self.buttonHash = Button(self.secondRow, text="#")
        self.buttonDol = Button(self.secondRow, text="$")
        self.buttonPerc = Button(self.secondRow, text="%")
        self.buttonCar = Button(self.secondRow, text="^")
        self.buttonAmp = Button(self.secondRow, text="&")
        self.buttonAst = Button(self.secondRow, text="*")
        self.buttonOpenParen = Button(self.secondRow, text="(")
        self.buttonCloseParen = Button(self.secondRow, text=")")
        self.returnButton = Button(self.secondRow, text=u"\u23CE")

        self.buttonTilde = Button(self.thirdRow, text="~")
        self.buttonUnderScore = Button(self.thirdRow, text="_")
        self.buttonPlus = Button(self.thirdRow, text="+")
        self.buttonMinus = Button(self.thirdRow, text="-")
        self.buttonEquals = Button(self.thirdRow, text="=")
        self.buttonOpenBracket = Button(self.thirdRow, text="{")
        self.buttonCloseBracket = Button(self.thirdRow, text="}")
        self.buttonLessThan = Button(self.thirdRow, text="<")
        self.buttonGreaterThan = Button(self.thirdRow, text=">")
        self.buttonBackSlash = Button(self.thirdRow, text="/")

        self.buttonAccent = Button(self.fourthRow, text="`")
        self.buttonPipe = Button(self.fourthRow, text="|")
        self.numButton = Button(self.fourthRow, text="ABC")
        self.spaceBar = Button(self.fourthRow, text="                               ")
        self.keyboardButton = Button(self.fourthRow, text=u"\u2328")
        self.buttonOpenBracket = Button(self.fourthRow, text="[")
        self.buttonCloseBracket = Button(self.fourthRow, text="]")

        self.button0.grid(row=0, column=0)
        self.button1.grid(row=0, column=1)
        self.button2.grid(row=0, column=2)
        self.button3.grid(row=0, column=3)
        self.button4.grid(row=0, column=4)
        self.button5.grid(row=0, column=5)
        self.button6.grid(row=0, column=6)
        self.button7.grid(row=0, column=7)
        self.button8.grid(row=0, column=8)
        self.button9.grid(row=0, column=9)
        self.deleteButton.grid(row=0, column=10)

        self.buttonExp.grid(row=0, column=0)
        self.buttonAt.grid(row=0, column=1)
        self.buttonHash.grid(row=0, column=2)
        self.buttonDol.grid(row=0, column=3)
        self.buttonPerc.grid(row=0, column=4)
        self.buttonCar.grid(row=0, column=5)
        self.buttonAmp.grid(row=0, column=6)
        self.buttonAst.grid(row=0, column=7)
        self.buttonOpenParen.grid(row=0, column=8)
        self.buttonCloseParen.grid(row=0, column=9)
        self.returnButton.grid(row=0, column=10)

        self.buttonTilde.grid(row=0, column=0)
        self.buttonUnderScore.grid(row=0, column=1)
        self.buttonPlus.grid(row=0, column=2)
        self.buttonMinus.grid(row=0, column=3)
        self.buttonEquals.grid(row=0, column=4)
        self.buttonOpenBracket.grid(row=0, column=5)
        self.buttonCloseBracket.grid(row=0, column=6)
        self.buttonLessThan.grid(row=0, column=7)
        self.buttonGreaterThan.grid(row=0, column=8)
        self.buttonBackSlash.grid(row=0, column=9)

        self.buttonAccent.grid(row=0, column=0)
        self.buttonPipe.grid(row=0, column=1)
        self.numButton.grid(row=0, column=2)
        self.spaceBar.grid(row=0, column=3)
        self.keyboardButton.grid(row=0, column=4)
        self.buttonOpenBracket.grid(row=0, column=5)
        self.buttonCloseBracket.grid(row=0, column=6)

        self.firstRow.grid_columnconfigure(0, weight=1)
        self.firstRow.grid_columnconfigure(1, weight=1)
        self.firstRow.grid_columnconfigure(2, weight=1)
        self.firstRow.grid_columnconfigure(3, weight=1)
        self.firstRow.grid_columnconfigure(4, weight=1)
        self.firstRow.grid_columnconfigure(5, weight=1)
        self.firstRow.grid_columnconfigure(6, weight=1)
        self.firstRow.grid_columnconfigure(7, weight=1)
        self.firstRow.grid_columnconfigure(8, weight=1)
        self.firstRow.grid_columnconfigure(9, weight=1)
        self.firstRow.grid_columnconfigure(10, weight=1)

        self.secondRow.grid_columnconfigure(0, weight=1)
        self.secondRow.grid_columnconfigure(1, weight=1)
        self.secondRow.grid_columnconfigure(2, weight=1)
        self.secondRow.grid_columnconfigure(3, weight=1)
        self.secondRow.grid_columnconfigure(4, weight=1)
        self.secondRow.grid_columnconfigure(5, weight=1)
        self.secondRow.grid_columnconfigure(6, weight=1)
        self.secondRow.grid_columnconfigure(7, weight=1)
        self.secondRow.grid_columnconfigure(8, weight=1)
        self.secondRow.grid_columnconfigure(9, weight=1)
        self.secondRow.grid_columnconfigure(10, weight=1)

        self.thirdRow.grid_columnconfigure(0, weight=1)
        self.thirdRow.grid_columnconfigure(1, weight=1)
        self.thirdRow.grid_columnconfigure(2, weight=1)
        self.thirdRow.grid_columnconfigure(3, weight=1)
        self.thirdRow.grid_columnconfigure(4, weight=1)
        self.thirdRow.grid_columnconfigure(5, weight=1)
        self.thirdRow.grid_columnconfigure(6, weight=1)
        self.thirdRow.grid_columnconfigure(7, weight=1)
        self.thirdRow.grid_columnconfigure(8, weight=1)
        self.thirdRow.grid_columnconfigure(9, weight=1)

        self.fourthRow.grid_columnconfigure(0, weight=1)
        self.fourthRow.grid_columnconfigure(1, weight=1)
        self.fourthRow.grid_columnconfigure(2, weight=1)
        self.fourthRow.grid_columnconfigure(3, weight=1)
        self.fourthRow.grid_columnconfigure(4, weight=1)
        self.fourthRow.grid_columnconfigure(5, weight=1)
        self.fourthRow.grid_columnconfigure(6, weight=1)
